// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handlers

import (
	"context"
	"github.com/mikenai/gowork/internal/models"
	"sync"
)

// Ensure, that UsersServiceMock does implement UsersService.
// If this is not the case, regenerate this file with moq.
var _ UsersService = &UsersServiceMock{}

// UsersServiceMock is a mock implementation of UsersService.
//
//	func TestSomethingThatUsesUsersService(t *testing.T) {
//
//		// make and configure a mocked UsersService
//		mockedUsersService := &UsersServiceMock{
//			CreateFunc: func(ctx context.Context, name string) (models.User, error) {
//				panic("mock out the Create method")
//			},
//			FetchFunc: func(ctx context.Context, id string) (models.User, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedUsersService in code that requires UsersService
//		// and then make assertions.
//
//	}
type UsersServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, name string) (models.User, error)

	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, id string) (models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockCreate sync.RWMutex
	lockFetch  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UsersServiceMock) Create(ctx context.Context, name string) (models.User, error) {
	if mock.CreateFunc == nil {
		panic("UsersServiceMock.CreateFunc: method is nil but UsersService.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, name)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUsersService.CreateCalls())
func (mock *UsersServiceMock) CreateCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Fetch calls FetchFunc.
func (mock *UsersServiceMock) Fetch(ctx context.Context, id string) (models.User, error) {
	if mock.FetchFunc == nil {
		panic("UsersServiceMock.FetchFunc: method is nil but UsersService.Fetch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, id)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedUsersService.FetchCalls())
func (mock *UsersServiceMock) FetchCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
